package com.salon.core.domain.enums;

public enum EventType {
    RESERVATION_CREATED,
    DEPOSIT_CREATED,
    DEPOSIT_PAID,
    RESERVATION_CONFIRMED,
    RESERVATION_CANCELED,
    DEPOSIT_REFUNDED,
    DEPOSIT_FORFEITED,
    RESERVATION_NO_SHOW,
    RESERVATION_COMPLETED,
    RESERVATION_PAYMENT_EXPIRED
}