package com.salon.core.domain.enums;

public enum EventType {
    RESERVATION_CREATED,
    RESERVATION_CONFIRMED,
    RESERVATION_COMPLETED,
    RESERVATION_CANCELED,
    NO_SHOW_MARKED,
    PENALTY_CALCULATED
}
