apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':core')
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
}

bootJar {
    archiveFileName = 'salon-admin.jar'
}
